create table users (
	id INT NOT NULL AUTO_INCREMENT,
    	email VARCHAR(100) NOT NULL,
    	password VARCHAR(100) NOT NULL,
    	username VARCHAR(100) NOT NULL,
    	bio VARCHAR(200) NOT NULL DEFAULT '个人简介',
   	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    	edited TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);
