create table likes (
    id INT NOT NULL AUTO_INCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    edited TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    userid INT NOT NULL,
    videoid INT NOT NULL,
    FOREIGN KEY fk_likes_userid(userid) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY fk_likes_videoid(videoid) REFERENCES videos(id) ON UPDATE CASCADE ON DELETE CASCADE,
    PRIMARY KEY (id));
